
version: '3.8'


services:

  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_USERNAME: nest-pokemon
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017